#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys

class MiseDCleaner:
    def __init__(self, path):
        self.path = path

    def run_fdupes(self):
        if os.path.isdir(self.path):
            # Ejecutar fdupes para encontrar y eliminar duplicados
            os.system(f"fdupes -d -N -l {self.path}duplicates_removed.txt {self.path}")

            # Eliminar archivos con el mismo nombre que los duplicados eliminados
            with open(f"{self.path}duplicates_removed.txt", "r") as file:
                for line in file:
                    # Obtener el nombre del archivo eliminado
                    filename = line.strip()
                    # Eliminar todos los archivos con el mismo nombre, independientemente de su extensión
                    for root, dirs, files in os.walk(self.path):
                        for file in files:
                            if os.path.splitext(file)[0] == os.path.splitext(filename)[0]:
                                os.remove(os.path.join(root, file))

            print("Removed duplicated mutants (only ktest) and associated files")
        else:
            print("Invalid path")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 mise-dcleaner.py <path>")
        sys.exit(1)

    path = sys.argv[1]
    cleaner = MiseDCleaner(path)
    cleaner.run_fdupes()